"""
Compare two documents (PDF or Word) and produce an HTML report
with additions highlighted in green and deletions in red.
"""
import difflib
import os
import tempfile

import fitz

from app.workers.celery_app import celery_app
from app.workers.base_task import PDFBaseTask, SyncSession
from app.db.models.job import Job, JobStatus, ToolType
from app.services.storage import storage


def _extract_text_by_page(path: str) -> list[str]:
    """Return list of text strings, one per page, from a PDF or Word file."""
    ext = os.path.splitext(path)[1].lower()

    if ext in (".doc", ".docx"):
        # Convert to PDF first via LibreOffice, then extract
        from app.workers.tasks.convert import libreoffice_convert
        tmpdir = os.path.dirname(path)
        pdf_path = libreoffice_convert(path, tmpdir, fmt="pdf")
        path = pdf_path

    doc = fitz.open(path)
    pages = [page.get_text("text") for page in doc]
    doc.close()
    return pages


def _build_html_report(pages_a: list[str], pages_b: list[str],
                        name_a: str, name_b: str) -> str:
    """Build a self-contained HTML diff report."""
    # Flatten to lines for difflib
    lines_a = []
    for i, page in enumerate(pages_a):
        lines_a.append(f"\n── Page {i + 1} ──\n")
        lines_a.extend(page.splitlines(keepends=True))

    lines_b = []
    for i, page in enumerate(pages_b):
        lines_b.append(f"\n── Page {i + 1} ──\n")
        lines_b.extend(page.splitlines(keepends=True))

    differ = difflib.HtmlDiff(wrapcolumn=80)
    table = differ.make_table(
        lines_a, lines_b,
        fromdesc=name_a, todesc=name_b,
        context=True, numlines=3,
    )

    # Count changes
    added = sum(1 for l in lines_b if l not in set(lines_a))
    removed = sum(1 for l in lines_a if l not in set(lines_b))

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Document Comparison: {name_a} vs {name_b}</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 0; background: #f5f5f5; }}
  .header {{ background: #1a73e8; color: white; padding: 20px 32px; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header p {{ margin: 6px 0 0; opacity: 0.85; font-size: 13px; }}
  .stats {{ display: flex; gap: 24px; padding: 16px 32px; background: white;
            border-bottom: 1px solid #e0e0e0; }}
  .stat {{ padding: 8px 16px; border-radius: 6px; font-size: 13px; font-weight: 600; }}
  .stat.added {{ background: #e6f4ea; color: #137333; }}
  .stat.removed {{ background: #fce8e6; color: #c5221f; }}
  .stat.unchanged {{ background: #f1f3f4; color: #5f6368; }}
  .diff-wrap {{ padding: 24px 32px; overflow-x: auto; }}
  table.diff {{ width: 100%; border-collapse: collapse; font-size: 12.5px;
                font-family: 'Courier New', monospace; background: white;
                border-radius: 8px; overflow: hidden;
                box-shadow: 0 1px 4px rgba(0,0,0,0.1); }}
  table.diff th {{ background: #1a73e8; color: white; padding: 10px 12px; text-align: left; }}
  table.diff td {{ padding: 3px 8px; vertical-align: top; border-bottom: 1px solid #f0f0f0; }}
  .diff_add {{ background: #e6f4ea; }}
  .diff_chg {{ background: #fef3cd; }}
  .diff_sub {{ background: #fce8e6; }}
  .diff_add td {{ color: #137333; }}
  .diff_sub td {{ color: #c5221f; }}
  span.diff_add {{ background: #a8d5b5; padding: 1px 2px; border-radius: 2px; }}
  span.diff_sub {{ background: #f5a8a3; padding: 1px 2px; border-radius: 2px;
                   text-decoration: line-through; }}
  td.diff_header {{ background: #f1f3f4; color: #5f6368; font-size: 11px; }}
  .footer {{ text-align: center; padding: 24px; color: #9aa0a6; font-size: 12px; }}
</style>
</head>
<body>
<div class="header">
  <h1>Document Comparison</h1>
  <p><strong>{name_a}</strong> &nbsp;vs&nbsp; <strong>{name_b}</strong></p>
</div>
<div class="stats">
  <div class="stat added">+ {added} additions</div>
  <div class="stat removed">− {removed} deletions</div>
</div>
<div class="diff-wrap">
{table}
</div>
<div class="footer">Generated by PDF Toolkit</div>
</body>
</html>"""
    return html


@celery_app.task(
    bind=True, base=PDFBaseTask,
    name="app.workers.tasks.compare.compare_docs_task",
    max_retries=1, soft_time_limit=300,
)
def compare_docs_task(self, job_id: str):
    self.update_job(job_id, status=JobStatus.PROCESSING, progress=10)

    with SyncSession() as session:
        job = session.get(Job, job_id)
        input_keys = job.input_keys
        options = dict(job.options)

    if len(input_keys) < 2:
        raise ValueError("Two input files are required for comparison")

    key_a, key_b = input_keys[0], input_keys[1]
    name_a = options.get("name_a", "Document A")
    name_b = options.get("name_b", "Document B")

    with tempfile.TemporaryDirectory() as tmpdir:
        # Detect extension from key
        ext_a = os.path.splitext(key_a)[1] or ".pdf"
        ext_b = os.path.splitext(key_b)[1] or ".pdf"

        path_a = os.path.join(tmpdir, f"doc_a{ext_a}")
        path_b = os.path.join(tmpdir, f"doc_b{ext_b}")

        storage.download_to_temp(key_a, path_a)
        self.update_job(job_id, progress=25)
        storage.download_to_temp(key_b, path_b)
        self.update_job(job_id, progress=40)

        pages_a = _extract_text_by_page(path_a)
        self.update_job(job_id, progress=60)
        pages_b = _extract_text_by_page(path_b)
        self.update_job(job_id, progress=75)

        html = _build_html_report(pages_a, pages_b, name_a, name_b)

        output_path = os.path.join(tmpdir, "comparison.html")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        self.update_job(job_id, progress=90)

        output_key = f"results/{job_id}/comparison.html"
        storage.upload_from_temp(output_path, output_key, content_type="text/html")

    with SyncSession() as session:
        job = session.get(Job, job_id)
        job.status = JobStatus.COMPLETED
        job.output_key = output_key
        job.progress = 100
        job.options = {**options, "output_filename": "comparison.html"}
        session.commit()

    return output_key
